hl:
  baseUrl: http://www.hl.co.uk/
  marketUrl: shares/stock-market-summary/ftse-all-share
  destinationFolder: data
  marketsToAnalyse:
    - FTSE All Share
    - FTSE AIM 100
  interestingTabs:
    - broker-forecast
    - director-deals
    - &financialTag financial-statements-and-reports
    - dividends
    - &companyInformationTag company-information
  financial:
    suffix: *financialTag
  companyInformation:
    suffix: *companyInformationTag
